In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('insurance_pre.csv')

In [3]:
dataset = pd.get_dummies(dataset, dtype=int, drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [4]:
independent = dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
dependent = dataset[['charges']]

In [5]:
from sklearn.ensemble import RandomForestRegressor

In [6]:
from sklearn.model_selection import GridSearchCV
param_grid = {'criterion':['squared_error','absolute_error','poisson'],
'max_features': ['auto','sqrt','log2'],
'n_estimators':[10,100,1000,2000,3000]}
grid = GridSearchCV(RandomForestRegressor(), param_grid, refit=True, verbose=3, n_jobs=-1)
grid.fit(independent, dependent)

Fitting 5 folds for each of 45 candidates, totalling 225 fits

C:\Users\MANONMANI\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:489: FitFailedWarning:
75 fits failed out of a total of 225.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
43 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\MANONMANI\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 851, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MANONMANI\anaconda3\Lib\site-packages\sklearn\base.py", line 1393, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\MANONMANI\anaconda3\Lib\site-packages\sklearn\base.py", line 554, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\MANONMANI\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

--------------------------------------------------------------------------------
32 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\MANONMANI\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 851, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MANONMANI\anaconda3\Lib\site-packages\sklearn\base.py", line 1393, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\MANONMANI\anaconda3\Lib\site-packages\sklearn\base.py", line 554, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\MANONMANI\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\MANONMANI\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:1234: UserWarning: One or more of the test scores are non-finite: [       nan        nan        nan        nan        nan 0.81809412
 0.83374348 0.83501281 0.83463696 0.83489801 0.81113534 0.83387336
 0.83422704 0.83526952 0.83523611        nan        nan        nan
        nan        nan 0.80923173 0.82861138 0.83115425 0.8320557
 0.83160839 0.81518649 0.82689343 0.83143635 0.83170445 0.83151318
        nan        nan        nan        nan        nan 0.81976881
 0.83439749 0.83538493 0.83456148 0.83495717 0.82350507 0.83272213
 0.83463538 0.83485814 0.83513228]
  warnings.warn(
C:\Users\MANONMANI\anaconda3\Lib\site-packages\sklearn\base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'absolute_error',
                                       'poisson'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'n_estimators': [10, 100, 1000, 2000, 3000]},
             verbose=3)

In [7]:
final = grid.cv_results_
grid_predict = grid.predict(independent)

In [8]:
from sklearn.metrics import r2_score
r_score = r2_score(grid_predict,dependent)
print('The R_Score value for the best parameter {}'.format(grid.best_params_),r_score)

The R_Score value for the best parameter {'criterion': 'poisson', 'max_features': 'sqrt', 'n_estimators': 1000} 0.9745624161772521

In [9]:
table = pd.DataFrame.from_dict(final)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.012250,0.003660,0.000000,0.000000,squared_error,auto,10,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,31
1,0.011900,0.005891,0.000000,0.000000,squared_error,auto,100,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,31
2,0.008700,0.004491,0.000000,0.000000,squared_error,auto,1000,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,31
3,0.007255,0.002791,0.000000,0.000000,squared_error,auto,2000,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,31
4,0.009280,0.005050,0.000000,0.000000,squared_error,auto,3000,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,31
5,0.301135,0.078306,0.040196,0.003036,squared_error,sqrt,10,"{'criterion': 'squared_error', 'max_features':...",0.847130,0.757012,0.853341,0.810644,0.822345,0.818094,0.034322,27
6,1.962298,0.063889,0.163915,0.010032,squared_error,sqrt,100,"{'criterion': 'squared_error', 'max_features':...",0.856135,0.777956,0.863616,0.830413,0.840596,0.833743,0.030213,15
7,15.100043,5.141534,1.119876,0.628460,squared_error,sqrt,1000,"{'criterion': 'squared_error', 'max_features':...",0.860073,0.780946,0.862143,0.830614,0.841288,0.835013,0.029482,5
8,31.418254,5.898078,1.582431,1.182588,squared_error,sqrt,2000,"{'criterion': 'squared_error', 'max_features':...",0.858904,0.780766,0.862206,0.829965,0.841343,0.834637,0.029386,9
9,21.929698,5.417216,0.954659,0.047673,squared_error,sqrt,3000,"{'criterion': 'squared_error', 'max_features':...",0.859472,0.781243,0.862079,0.830210,0.841486,0.834898,0.029281,7
10,0.253871,0.016232,0.042576,0.003462,squared_error,log2,10,"{'criterion': 'squared_error', 'max_features':...",0.824185,0.764790,0.835587,0.805875,0.825239,0.811135,0.025070,29
11,1.738237,0.405309,0.159514,0.064407,squared_error,log2,100,"{'criterion': 'squared_error', 'max_features':...",0.858226,0.779767,0.863334,0.830016,0.838024,0.833873,0.029734,14
12,15.209579,3.437153,0.763287,0.566021,squared_error,log2,1000,"{'criterion': 'squared_error', 'max_features':...",0.860114,0.779832,0.860976,0.830797,0.839417,0.834227,0.029608,13
13,25.088233,6.507677,1.022890,0.844672,squared_error,log2,2000,"{'criterion': 'squared_error', 'max_features':...",0.859727,0.780810,0.862655,0.830345,0.842811,0.835270,0.029648,2
14,37.944955,11.344291,2.316723,0.718640,squared_error,log2,3000,"{'criterion': 'squared_error', 'max_features':...",0.859890,0.780485,0.862612,0.830767,0.842428,0.835236,0.029754,3
15,0.007977,0.003709,0.000000,0.000000,absolute_error,auto,10,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,31
16,0.009556,0.001495,0.000000,0.000000,absolute_error,auto,100,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,31
17,0.016121,0.005225,0.000000,0.000000,absolute_error,auto,1000,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,31
18,0.006113,0.004941,0.000000,0.000000,absolute_error,auto,2000,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,31
19,0.009477,0.003553,0.000000,0.000000,absolute_error,auto,3000,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,31
20,0.450435,0.025964,0.039328,0.006819,absolute_error,sqrt,10,"{'criterion': 'absolute_error', 'max_features'...",0.833776,0.757490,0.821842,0.819533,0.813517,0.809232,0.026695,30
21,3.964448,0.053262,0.150521,0.009255,absolute_error,sqrt,100,"{'criterion': 'absolute_error', 'max_features'...",0.855183,0.770619,0.852070,0.826141,0.839045,0.828611,0.030772,23
22,20.695008,9.846365,0.511014,0.300983,absolute_error,sqrt,1000,"{'criterion': 'absolute_error', 'max_features'...",0.855672,0.776892,0.854236,0.826917,0.842054,0.831154,0.029035,22
23,42.584115,17.221082,1.207808,0.661278,absolute_error,sqrt,2000,"{'criterion': 'absolute_error', 'max_features'...",0.855995,0.779638,0.854970,0.827544,0.842132,0.832056,0.028170,17
24,75.016793,5.642290,1.447919,1.001300,absolute_error,sqrt,3000,"{'criterion': 'absolute_error', 'max_features'...",0.854956,0.777935,0.854808,0.827897,0.842447,0.831608,0.028620,19
25,0.614747,0.368513,0.023027,0.034288,absolute_error,log2,10,"{'criterion': 'absolute_error', 'max_features'...",0.843361,0.762104,0.835345,0.808016,0.827107,0.815186,0.029022,28
26,2.682029,0.070431,0.103583,0.039386,absolute_error,log2,100,"{'criterion': 'absolute_error', 'max_features'...",0.849175,0.772171,0.847448,0.820751,0.844922,0.826893,0.029245,24
27,26.737780,0.425391,0.920046,0.040851,absolute_error,log2,1000,"{'criterion': 'absolute_error', 'max_features'...",0.854274,0.777294,0.854386,0.827995,0.843233,0.831436,0.028742,21
28,48.084528,8.284937,1.296214,0.684203,absolute_error,log2,2000,"{'criterion': 'absolute_error', 'max_features'...",0.855190,0.778343,0.853988,0.828428,0.842574,0.831704,0.028371,18
29,65.867769,21.008872,1.785063,0.943279,absolute_error,log2,3000,"{'criterion': 'absolute_error', 'max_features'...",0.855857,0.777097,0.853681,0.828639,0.842291,0.831513,0.028878,20
30,0.001357,0.000047,0.000000,0.000000,poisson,auto,10,"{'criterion': 'poisson', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,31
31,0.021606,0.040412,0.000000,0.000000,poisson,auto,100,"{'criterion': 'poisson', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,31
32,0.001862,0.000214,0.000000,0.000000,poisson,auto,1000,"{'criterion': 'poisson', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,31
33,0.020844,0.038249,0.000000,0.000000,poisson,auto,2000,"{'criterion': 'poisson', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,31
34,0.001361,0.000147,0.000000,0.000000,poisson,auto,3000,"{'criterion': 'poisson', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,31
35,0.225232,0.006197,0.005815,0.000095,poisson,sqrt,10,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.849459,0.756973,0.845847,0.821405,0.825162,0.819769,0.033277,26
36,1.340672,0.036362,0.099264,0.037236,poisson,sqrt,100,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.860513,0.780896,0.859779,0.831125,0.839675,0.834397,0.029076,12
37,12.835423,0.063389,0.911907,0.008682,poisson,sqrt,1000,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.860909,0.782371,0.861812,0.830620,0.841212,0.835385,0.029042,1
38,23.622730,2.395743,1.306652,0.706427,poisson,sqrt,2000,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.859882,0.780028,0.861638,0.829779,0.841481,0.834561,0.029728,11
39,22.356677,12.454938,1.528036,1.073720,poisson,sqrt,3000,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.859528,0.780964,0.862145,0.830117,0.842032,0.834957,0.029433,6
40,0.268176,0.076440,0.060279,0.044866,poisson,log2,10,"{'criterion': 'poisson', 'max_features': 'log2...",0.848731,0.758417,0.845357,0.821241,0.843778,0.823505,0.033960,25
41,1.305283,0.047054,0.104451,0.038589,poisson,log2,100,"{'criterion': 'poisson', 'max_features': 'log2...",0.856020,0.780951,0.858800,0.829217,0.838621,0.832722,0.028108,16
42,10.890195,2.292078,0.631284,0.339380,poisson,log2,1000,"{'criterion': 'poisson', 'max_features': 'log2...",0.858809,0.781233,0.862145,0.830155,0.840834,0.834635,0.029160,10
43,24.760584,0.741017,1.484850,0.243930,poisson,log2,2000,"{'criterion': 'poisson', 'max_features': 'log2...",0.859331,0.781173,0.862646,0.829959,0.841181,0.834858,0.029384,8
44,26.565437,2.512082,1.206404,0.236276,poisson,log2,3000,"{'criterion': 'poisson', 'max_features': 'log2...",0.859750,0.782118,0.861594,0.830565,0.841634,0.835132,0.028913,4

In [10]:
age=int(input('Enter the age:'))
bmi=float(input('Enter the bmi:'))
child=int(input('Enter the children:'))
gender=int(input('Enter the gender male(0) or female(1):'))
smoker=int(input('Enter the smoker yes(1) or no(0):'))
Future_prediction = grid.predict([[age,bmi,child,gender,smoker]])
print("insurance prediction = {}".format(Future_prediction))

Enter the age: 39
Enter the bmi: 30
Enter the children: 2
Enter the gender male(0) or female(1): 0
Enter the smoker yes(1) or no(0): 0

C:\Users\MANONMANI\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

insurance prediction = [7008.30928949]